node {
    def mvnHome
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git 'https://github.com/aldos2002/springMVC/'
        // Get the Maven tool.
        // ** NOTE: This 'M3' Maven tool must be configured
        // **       in the global configuration.
        mvnHome = tool 'maven'
    }
    stage('Build') {
        // Run the maven build
        if (isUnix()) {
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.skip=true -s settings.xml clean install"
        } else {
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
        }
    }
    stage('Deploy') {
        // Deploy to tomcat
        sh "'${mvnHome}/bin/mvn' -s settings.xml tomcat7:redeploy-only"
    }
    stage('Test') {
        // Run cucumber tests
        sh "'${mvnHome}/bin/mvn' -s settings.xml test"
    }
}