# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
#
# Install docker for Mac:
# https://www.docker.com/products/docker
#
# docker-compose -p local_jenkins down
# docker-compose -p local_jenkins up -d
# docker-compose -p local_jenkins logs
#
# Use the password from the logs output to access the instance.
# http://localhost:49001/
# ------------------------------------------------------------------------------
version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "8081:8080"
      - "50001:50000"
    restart: "always"
    volumes:
      - "f:/docker/jenkins:/var/jenkins_home"
#  sonarqube:
#      #container_name: sonarqube
#      image: sonarqube
#      ports:
#       - "9000:9000"
#       - "9092:9092"
  tomcat:
        image: "tomcat:8.0"
        ports:
         - "8888:8080"
        volumes:
         - "f:/docker/tomcat/conf:/usr/local/tomcat/conf"